# Generated by Django 2.0.13 on 2021-11-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('price', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2021-01-01 00:00:00.000000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
